#!/bin/bash


ask() {
  # https://djm.me/ask

  local prompt default reply

  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo -n "$1 [$prompt] "

    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read reply </dev/tty

    # Default?
    if [ -z "$reply" ]; then
      reply=$default
    fi

    # Check if the reply is valid
    case "$reply" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}


for x in $(find . -type d) ; do
  if [ -d "${x}/.git" ] ; then
    cd "${x}"
    origin="$(git config --get remote.origin.url)"
    cd - 1>/dev/null
    echo git submodule add "${origin}" "${x}"
    if [[ $origin == *"git@github.com:Gigahawk/dotfiles.git"* ]] ; then
      echo Skipping main directory
      continue
    fi
    if [ "$1" == "--ask" ] ; then
      if ask "Add this submodule?" Y ; then
          git submodule add "${origin}" "${x}"
      fi
    else
      git submodule add "${origin}" "${x}"
    fi
  fi
done

