#!/bin/bash

export EDITOR="mimeopen"

export FFF_OPENER="xdg-open"

export FFF_CD_ON_EXIT=1

export FFF_MARK_FORMAT="> %f"

export FFF_OPENER="mimeopen"

f() {
  fff "$@"
  cd "$(cat "${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d")"
}
